apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: logging
spec:
  selector:
    app: opensearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.13.0
          env:
            - name: discovery.type
              value: single-node
            - name: plugins.security.disabled
              value: "true"
          ports:
            - containerPort: 9200
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
